### ISSUE TITLE
表記が統一されていない

### ISSUE THREAD

**Issue by harxki** [naoikun/rails1st#23]
https://group-schedules.herokuapp.com/users/new
ではh1タグにSign upと英語で書かれているが
https://group-schedules.herokuapp.com/signin
ではh1タグにサインインと日本語で記述されている

**Comment by naoikun** [comment]
指摘箇所だけ修正:8518aa93cc834b416054fa4f03790ac9f1ee5e8b
他にも表記揺れがあるので今後修正する必要がある。
